version: "3"

services:
  set-api:
    container_name: set-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.Api
    volumes:
      - ./data:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9002:80
